export enum CommonEnum {
  CREATE = 'create',
  UPDATE = 'update',
  PERMISSION_MENU = 1,
  PERMISSION_BUTTON = 2,
  STATUS_ENABLE = 1,
  STATUS_DISABLE = 2,
  SUCCESS_CODE = '00000',
  TYPE_ANY = 1,
  TYPE_LESS = 2,
  TYPE_LESS_EQUAL = 3,
  TYPE_EQUAL = 4,
  TYPE_GREATER = 5,
  TYPE_GREATER_EQUAL = 6
}
