export enum StatusEnum {

    INIT=0,

    IMPORTED = 1,

    WRITTEN_OFF = 2,

    PRE_TAX_DEDUCTION = 3,

    WAITING_OVERDUE_ONE_YEAR = 4,

    WAITING_BANKRUPTCY_THREE_YEARS = 5,

    WAITING_CLOSE_THREE_YEARS = 6,

    WAITING_REVOKE_THREE_YEARS = 7,

    WAITING_STOP_OPERATION_THREE_YEARS = 8,

    WAITING_DEATH_THREE_YEARS = 9,

    WAITING_INCAPACITATED_THREE_YEARS = 10,

    WAITING_MISSING_THREE_YEARS = 11,

    WAITING_INVESTIGATION_TWO_YEARS = 12,

    WAITING_EVIDENCE_YEARS = 13,

    WAITING_LAW_YEARS = 14,

    DECLARE_PRE_TAX_DEDUCTION = 15,

    WAITING_DECLARE = 16,

    REVOKE_VERIFY_SUCCESS = 17,

    REVOKE_DECLARE=18,


    LAWS_REGULATIONS_UNPUBLISHED = 1,

    LAWS_REGULATIONS_PUBLISHED = 2,
    LAWS_REGULATIONS_OFF_SHELF = 3
}
