export enum TypeEnum {

    FILE_ACCOUNT_DOCUMENT = 1,

    FILE_CONFIRM_EVIDENCE = 2,

    FILE_BAD_DEBT_APPROVE = 3,

    FILE_BAD_DEBT_APPLY = 4,

    FILE_LOAN_CONTRACT = 5,

    FILE_LOAN_CERTIFICATE = 6,

    FILE_LOAN_ACCOUNT_DOCUMENT = 7,

    FILE_REVOKE_ACCOUNT_DOCUMENT = 8,

    FILE_RISK_FIVE_LEVEL = 9,

    FILE_LOAN_BALANCE_QUERY = 10,

    FILE_OTHER_APPLICATION_MATERIALS = 11,

    WRITE_OFF_RESULT = 1,

    REVOKE_RESULT = 2,

    SYS_ADD = 1,

    REVOKE_ADD = 2
}
